spring.application.name=taskflow

logging.level.root=warn
spring.main.banner-mode=off
spring.security.user.name=admin
spring.security.user.password=root

spring.datasource.url=jdbc:postgresql://localhost:5433/app
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000
jwt.secret-key=f465d8dbc390d7a128aae9e8d1f98230